### ISSUE TITLE
Flash  Game

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#172]
When creating a flash game, I set the date  and time as 2018-07-04 at 7:00am. It created the game immediately.

**Comment by shreyansjain** [comment]
Once I release a new version (v1.0.1.0), can you test it again?

**Comment by shreyansjain** [comment]
Sorry, ignore the above message. Meant for a different issue

**Comment by anmolg** [comment]
Can you please indicate the game details that you made?

**Comment by EhJay22** [comment]
It was created around 7:50am this morning and it was set to start at 8:10am I believe
Company: Laser Tag House
User: LaserTag
Game type: Flash

**Comment by anmolg** [comment]
Should be resolved

**Comment by EhJay22** [comment]
@anmolg I logged  out and in. I created a flash game this morning at approx 8:10 for Paintballtopia and it was supposed  to start at 8:18. It hasn't shown up yet.

**Comment by EhJay22** [comment]
Created a game today with Breakfast Cafe at 7:49. It was supposed to start at 7:54. Still not showing up.
Created another game with Pizza House at 7:58 and it was supposed to start right away. Still not showing up.

**Comment by anmolg** [comment]
More changes have been deployed. Can you verify now?

**Comment by EhJay22** [comment]
I will try it out, but I'm hitting a little snag.
It's blocking me out from creating a flash game for today. The current date is blocked out. I tried to move the time to 9:00PM on today's date, and it won't let me. So I currently can't test except for tomorrow

**Comment by EhJay22** [comment]
I also created a game last night for this morning to start at 8:00AM and I'm not seeing it now. 

So it looks like there's two bugs with this.

**Comment by anmolg** [comment]
I also created a game last night for this morning to start at 8:00AM and I'm not seeing it now.

Game details please. The latest starting flash game was 7.58am on 10 July which is > 3 days ago and  not at 8am you stated

**Comment by EhJay22** [comment]
Alright I still can't create a game on the day of.

But, I just created a game with Haute Clothing at 7:35PM
And it is set to start tomorrow at 8:01AM

**Comment by EhJay22** [comment]
Fixed
